# Generated by Django 5.0.7 on 2025-11-05 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('artist_name', models.CharField(max_length=100)),
                ('art_type', models.CharField(choices=[('Painting', 'Painting'), ('Sculpture', 'Sculpture')], max_length=20)),
                ('dimensions', models.CharField(max_length=50)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography')], max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('issue_number', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Mint', 'Mint'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=10)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('fashion_type', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Dress', 'Dress'), ('Jacket', 'Jacket')], max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('jewellery_type', models.CharField(choices=[('Necklace', 'Necklace'), ('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('Earrings', 'Earrings')], max_length=20)),
                ('material', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Gemstone', 'Gemstone')], max_length=20)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('director', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('DVD', 'DVD'), ('Blu-ray', 'Blu-ray'), ('Digital', 'Digital')], max_length=20)),
                ('genre', models.CharField(max_length=50)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('artist_name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('Vinyl', 'Vinyl'), ('CD', 'CD'), ('Cassette', 'Cassette')], max_length=20)),
                ('genre', models.CharField(max_length=50)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.product')),
                ('sport_type', models.CharField(choices=[('Equipment', 'Equipment'), ('Memorabilia', 'Memorabilia')], max_length=20)),
                ('sport_name', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
            ],
            bases=('auctions.product',),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
